# -*- coding: utf-8 -*-
"""
bpgen - generador de texto de pegado (T3D) para grafos de Blueprint.

Python puro, no necesita el editor. Se usa porque la API de Python de UE no
puede crear logica de Blueprint: UEdGraphPin no es un UObject, asi que no hay
forma de crear pines ni conexiones. Lo unico que entiende el editor es el
texto que se pega con Ctrl+V.

Nota util: al pegar, K2Node_CallFunction reconstruye sus pines a partir de la
FunctionReference y luego empareja por NOMBRE los datos pegados. O sea que no
hace falta declarar todos los pines de una funcion: basta con los que se
conectan o llevan valor. Lo que si tiene que estar bien es el nombre del pin;
uno mal escrito se convierte en un pin huerfano que compila sin quejarse.

Reconstruido el 2026-08-26 (el bpgen.py original se perdio con Tools/).
"""

import hashlib
import re

# --------------------------------------------------------------- utilidades

_counter = [0]


def guid(seed=None):
    """GUID de 32 hex. Determinista si se le da semilla, para que reejecutar
    el generador produzca exactamente el mismo texto (util con git)."""
    if seed is None:
        _counter[0] += 1
        seed = "auto_%d" % _counter[0]
    return hashlib.md5(seed.encode("utf-8")).hexdigest().upper()


def cls(path):
    """Referencia a una UClass tal y como la escribe el exportador de UE."""
    return "Class'\"%s\"'" % path


def obj(kind, path):
    return "%s'\"%s\"'" % (kind, path)


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _ruta_pelada(v):
    """Acepta Class'"/ruta"', "/ruta" o /ruta y devuelve siempre "/ruta"."""
    v = str(v).strip()
    m = re.match(r"^\w+'\"?(.*?)\"?'$", v)
    if m:
        v = m.group(1)
    v = v.strip('"')
    return '"%s"' % v


# ------------------------------------------------------------------- pines

CAT_EXEC = "exec"
CAT_BOOL = "bool"
CAT_INT = "int"
CAT_REAL = "real"
CAT_STRING = "string"
CAT_NAME = "name"
CAT_OBJECT = "object"
CAT_CLASS = "class"
CAT_STRUCT = "struct"
CAT_BYTE = "byte"
CAT_TEXT = "text"
CAT_DELEGATE = "delegate"
CAT_WILDCARD = "wildcard"


class Pin(object):
    def __init__(self, node, name, category, out=False, sub=None, sub_object=None,
                 default=None, hidden=False, container=None, is_ref=False,
                 friendly=None):
        self.node = node
        self.name = name
        self.category = category
        self.out = out
        self.sub = sub or ""
        self.sub_object = sub_object
        self.default = default
        self.hidden = hidden
        self.container = container
        self.is_ref = is_ref
        self.friendly = friendly
        self.links = []
        self.id = guid("%s|%s|%s" % (node.graph.name, node.name, name))

    # -- conexiones
    def to(self, other):
        """Conecta este pin con otro (bidireccional, como hace el editor)."""
        if other not in self.links:
            self.links.append(other)
        if self not in other.links:
            other.links.append(self)
        return other

    def render(self):
        p = ['PinId=%s' % self.id, 'PinName="%s"' % esc(self.name)]
        if self.friendly:
            p.append('PinFriendlyName=NSLOCTEXT("", "", "%s")' % esc(self.friendly))
        if self.out:
            p.append('Direction="EGPD_Output"')
        p.append('PinType.PinCategory="%s"' % self.category)
        p.append('PinType.PinSubCategory="%s"' % self.sub)
        p.append('PinType.PinSubCategoryObject=%s'
                 % (self.sub_object if self.sub_object else "None"))
        p.append('PinType.PinSubCategoryMemberReference=()')
        p.append('PinType.PinValueType=()')
        p.append('PinType.ContainerType=%s'
                 % (self.container if self.container else "None"))
        p.append('PinType.bIsReference=%s' % ("True" if self.is_ref else "False"))
        p.append('PinType.bIsConst=False')
        p.append('PinType.bIsWeakPointer=False')
        p.append('PinType.bIsUObjectWrapper=False')
        p.append('PinType.bSerializeAsSinglePrecisionFloat=False')
        if self.default is not None:
            # TRAMPA 1: NO escribir tambien AutogeneratedDefaultValue con el
            # mismo valor. Al reconstruir el nodo, Unreal considera que un pin
            # cuyo DefaultValue coincide con el autogenerado "no esta tocado" y
            # lo repone al valor de fabrica de la funcion. Con eso se perdian
            # TODOS los literales: las comparaciones de estado quedaban en 0,
            # AcceptanceRadius en -1 y los PrintString decian "Hello".
            #
            # TRAMPA 2: los pines de FText usan DefaultTextValue, no
            # DefaultValue. Y FText NO es un ScriptStruct: ponerle
            # PinSubCategoryObject=ScriptStruct'/Script/CoreUObject.Text' hace
            # que la referencia no resuelva y Unreal DESCARTA EL NODO ENTERO al
            # pegar, en silencio. Asi se perdieron los 5 SetText.
            # Ambas medidas el 2026-08-27.
            if self.category in (CAT_OBJECT, CAT_CLASS):
                # TRAMPA 3: DefaultObject quiere la RUTA PELADA entre comillas
                #   DefaultObject="/Script/AIModule.AISense_Sight"
                # NO el envoltorio Kind'"ruta"' que usa PinSubCategoryObject.
                # Con el envoltorio, el importador suelta
                #   Missing opening '"' in string property value
                #   Warning: B: Parse error while importing property values
                # y a continuacion revienta un ensure en EdGraphUtilities.cpp
                # (ThisPin), que ABORTA EL EMPAREJADO DE PINES DEL PEGADO
                # ENTERO: los 194 nodos entran pero se quedan con enlaces
                # colgados y el compilador escupe "El pin en uso <Unnamed> ya
                # no existe en el nodo Ev_*" para cada llamada a evento.
                # Un solo pin mal escrito tumba todo el grafo.
                # Medido el 2026-08-31.
                p.append('DefaultObject=%s' % _ruta_pelada(self.default))
            elif self.category == CAT_TEXT:
                p.append('DefaultTextValue=NSLOCTEXT("", "", "%s")'
                         % esc(str(self.default)))
            else:
                p.append('DefaultValue="%s"' % esc(str(self.default)))
        if self.links:
            p.append('LinkedTo=(%s)'
                     % "".join("%s %s," % (l.node.name, l.id) for l in self.links))
        p.append('PersistentGuid=00000000000000000000000000000000')
        p.append('bHidden=%s' % ("True" if self.hidden else "False"))
        p.append('bNotConnectable=False')
        p.append('bDefaultValueIsReadOnly=False')
        p.append('bDefaultValueIsIgnored=False')
        p.append('bAdvancedView=False')
        p.append('bOrphanedPin=False')
        return "   CustomProperties Pin (%s,)" % ",".join(p)


# ------------------------------------------------------------------- nodos

class Node(object):
    def __init__(self, graph, ue_class, name, x=0, y=0, props=None,
                 module="BlueprintGraph"):
        self.graph = graph
        self.ue_class = ue_class
        self.name = name
        self.x = x
        self.y = y
        self.props = props or {}
        self.module = module
        self.pins = []
        self.guid = guid("%s|%s" % (graph.name, name))
        graph.nodes.append(self)

    def pin(self, name, category=CAT_EXEC, **kw):
        p = Pin(self, name, category, **kw)
        self.pins.append(p)
        return p

    def get(self, name):
        for p in self.pins:
            if p.name == name:
                return p
        raise KeyError("el nodo %s no tiene el pin %r" % (self.name, name))

    # atajos habituales
    @property
    def exec_in(self):
        return self.get("execute")

    @property
    def exec_out(self):
        return self.get("then")

    def render(self):
        out = ['Begin Object Class=/Script/%s.%s Name="%s"'
               % (self.module, self.ue_class, self.name)]
        for k, v in self.props.items():
            out.append("   %s=%s" % (k, v))
        out.append("   NodePosX=%d" % self.x)
        out.append("   NodePosY=%d" % self.y)
        out.append("   NodeGuid=%s" % self.guid)
        for p in self.pins:
            out.append(p.render())
        out.append("End Object")
        return "\n".join(out)


class Graph(object):
    def __init__(self, name, titulo=""):
        self.name = name
        self.titulo = titulo
        self.nodes = []
        self._n = 0
        self._sufijo = "".join(c for c in name if c.isalnum())[-6:] + "_"

    def _auto(self, prefix):
        """El nombre lleva un prefijo del grafo para que dos pegados
        distintos nunca colisionen si se concatenan en un solo fichero
        (LinkedTo referencia los nodos POR NOMBRE)."""
        self._n += 1
        return "%s_%s%d" % (prefix, self._sufijo, self._n)

    # ---------------------------------------------------------- constructores
    def event(self, member_name, parent_class, x=0, y=0):
        """Evento heredado que se sobreescribe (BeginPlay, Tick...)."""
        n = Node(self, "K2Node_Event", self._auto("K2Node_Event"), x, y, {
            "EventReference": "(MemberParent=%s,MemberName=\"%s\")"
                              % (cls(parent_class), member_name),
            "bOverrideFunction": "True",
        })
        n.pin("then", CAT_EXEC, out=True)
        return n

    def custom_event(self, event_name, x=0, y=0):
        n = Node(self, "K2Node_CustomEvent", self._auto("K2Node_CustomEvent"), x, y, {
            "CustomFunctionName": '"%s"' % event_name,
        })
        n.pin("then", CAT_EXEC, out=True)
        return n

    def call(self, member_name, parent_class, x=0, y=0, pure=False,
             node_class="K2Node_CallFunction"):
        """Llamada a funcion. Al pegar, el nodo reconstruye sus pines desde la
        firma real; aqui solo hay que declarar los que se usan."""
        n = Node(self, node_class, self._auto(node_class), x, y, {
            "FunctionReference": "(MemberParent=%s,MemberName=\"%s\")"
                                 % (cls(parent_class), member_name),
        })
        if not pure:
            n.pin("execute", CAT_EXEC)
            n.pin("then", CAT_EXEC, out=True)
        return n

    def call_self(self, member_name, self_class, x=0, y=0, pure=False):
        """Llamada a una funcion/evento del propio Blueprint."""
        n = Node(self, "K2Node_CallFunction", self._auto("K2Node_CallFunction"), x, y, {
            "FunctionReference": "(MemberName=\"%s\",bSelfContext=True)" % member_name,
        })
        if not pure:
            n.pin("execute", CAT_EXEC)
            n.pin("then", CAT_EXEC, out=True)
        return n

    def var_get(self, var_name, category, x=0, y=0, sub_object=None, sub=None,
                container=None):
        n = Node(self, "K2Node_VariableGet", self._auto("K2Node_VariableGet"), x, y, {
            "VariableReference": "(MemberName=\"%s\",bSelfContext=True)" % var_name,
        })
        n.pin(var_name, category, out=True, sub_object=sub_object, sub=sub,
              container=container)
        return n

    def var_set(self, var_name, category, x=0, y=0, sub_object=None, sub=None,
                container=None):
        n = Node(self, "K2Node_VariableSet", self._auto("K2Node_VariableSet"), x, y, {
            "VariableReference": "(MemberName=\"%s\",bSelfContext=True)" % var_name,
        })
        n.pin("execute", CAT_EXEC)
        n.pin("then", CAT_EXEC, out=True)
        n.pin(var_name, category, sub_object=sub_object, sub=sub, container=container)
        n.pin("Output_Get", category, out=True, sub_object=sub_object, sub=sub,
              container=container)
        return n

    def var_get_target(self, var_name, category, owner_class, x=0, y=0,
                       sub_object=None, sub=None, container=None):
        """Lee una variable de OTRO objeto (pin 'self' de destino)."""
        n = Node(self, "K2Node_VariableGet", self._auto("K2Node_VariableGet"), x, y, {
            "VariableReference": "(MemberParent=%s,MemberName=\"%s\")"
                                 % (cls(owner_class), var_name),
        })
        n.pin("self", CAT_OBJECT, sub_object=cls(owner_class))
        n.pin(var_name, category, out=True, sub_object=sub_object, sub=sub,
              container=container)
        return n

    def var_set_target(self, var_name, category, owner_class, x=0, y=0,
                       sub_object=None, sub=None, container=None):
        """Escribe una variable de OTRO objeto."""
        n = Node(self, "K2Node_VariableSet", self._auto("K2Node_VariableSet"), x, y, {
            "VariableReference": "(MemberParent=%s,MemberName=\"%s\")"
                                 % (cls(owner_class), var_name),
        })
        n.pin("execute", CAT_EXEC)
        n.pin("then", CAT_EXEC, out=True)
        n.pin("self", CAT_OBJECT, sub_object=cls(owner_class))
        n.pin(var_name, category, sub_object=sub_object, sub=sub,
              container=container)
        n.pin("Output_Get", category, out=True, sub_object=sub_object, sub=sub,
              container=container)
        return n

    def component_bound_event(self, comp_name, delegate_name, delegate_owner,
                              bp_name, x=0, y=0):
        """El evento rojo que sale del '+' de un componente en el panel de
        detalles. Evita tener que montar Bind Event + Create Delegate."""
        fn = ("BndEvt__%s_%s_K2Node_ComponentBoundEvent_0_%s__DelegateSignature"
              % (bp_name, comp_name, delegate_name))
        n = Node(self, "K2Node_ComponentBoundEvent",
                 self._auto("K2Node_ComponentBoundEvent"), x, y, {
                     "ComponentPropertyName": '"%s"' % comp_name,
                     "DelegatePropertyName": '"%s"' % delegate_name,
                     "DelegateOwnerClass": cls(delegate_owner),
                     "EventReference": "(MemberParent=%s,MemberName=\"%s__DelegateSignature\")"
                                       % (cls(delegate_owner), delegate_name),
                     "CustomFunctionName": '"%s"' % fn,
                     "bOverrideFunction": "False",
                     "bInternalEvent": "True",
                 })
        n.pin("then", CAT_EXEC, out=True)
        return n

    def message(self, function_name, interface_class, x=0, y=0):
        """Llamada a una funcion de interfaz (el nodo con el sobre)."""
        n = Node(self, "K2Node_Message", self._auto("K2Node_Message"), x, y, {
            "FunctionReference": "(MemberParent=%s,MemberName=\"%s\")"
                                 % (cls(interface_class), function_name),
        })
        n.pin("execute", CAT_EXEC)
        n.pin("then", CAT_EXEC, out=True)
        return n

    def cast(self, target_class_path, x=0, y=0):
        n = Node(self, "K2Node_DynamicCast", self._auto("K2Node_DynamicCast"), x, y, {
            "TargetType": cls(target_class_path),
        })
        n.pin("execute", CAT_EXEC)
        n.pin("then", CAT_EXEC, out=True)
        n.pin("CastFailed", CAT_EXEC, out=True)
        n.pin("Object", CAT_OBJECT, sub_object=cls("/Script/CoreUObject.Object"))
        n.pin("AsTarget", CAT_OBJECT, out=True, sub_object=cls(target_class_path))
        n.pin("bSuccess", CAT_BOOL, out=True, hidden=True)
        return n

    def branch(self, x=0, y=0):
        n = Node(self, "K2Node_IfThenElse", self._auto("K2Node_IfThenElse"), x, y)
        n.pin("execute", CAT_EXEC)
        n.pin("Condition", CAT_BOOL)
        n.pin("then", CAT_EXEC, out=True)
        n.pin("else", CAT_EXEC, out=True)
        return n

    def self_node(self, x=0, y=0):
        n = Node(self, "K2Node_Self", self._auto("K2Node_Self"), x, y)
        n.pin("self", CAT_OBJECT, out=True)
        return n

    def switch_enum(self, enum_path, entradas, x=0, y=0):
        """Switch sobre un UserDefinedEnum. 'entradas' son los nombres INTERNOS
        (NewEnumerator0, NewEnumerator1, ...), no los de display."""
        n = Node(self, "K2Node_SwitchEnum", self._auto("K2Node_SwitchEnum"), x, y, {
            "Enum": obj("Enum", enum_path),
            "bHasDefaultPin": "False",
        })
        n.pin("execute", CAT_EXEC)
        n.pin("Selection", CAT_BYTE, sub_object=obj("Enum", enum_path))
        for e in entradas:
            n.pin(e, CAT_EXEC, out=True)
        return n

    def make_array(self, n_entradas, category, x=0, y=0, sub_object=None,
                   sub=None):
        """Nodo Make Array. El numero de entradas va en la propiedad
        NumInputs; los pines se llaman "[0]", "[1]"... y la SALIDA se llama
        "Array" (no "ReturnValue")."""
        n = Node(self, "K2Node_MakeArray", self._auto("K2Node_MakeArray"), x, y, {
            "NumInputs": str(n_entradas),
        })
        n.pin("Array", category, out=True, sub_object=sub_object, sub=sub,
              container="Array")
        for i in range(n_entradas):
            n.pin("[%d]" % i, category, sub_object=sub_object, sub=sub)
        return n

    def make_struct(self, struct_path, x=0, y=0):
        n = Node(self, "K2Node_MakeStruct", self._auto("K2Node_MakeStruct"), x, y, {
            "StructType": obj("ScriptStruct", struct_path),
            "bMadeAfterOverridePinRemoval": "True",
        })
        n.pin("StructOut", CAT_STRUCT, out=True,
              sub_object=obj("ScriptStruct", struct_path))
        return n

    def break_struct(self, struct_path, nombre_pin_entrada, x=0, y=0):
        """El pin de entrada de un Break se llama como el struct
        (p.ej. 'AIStimulus'), no 'InStruct'."""
        n = Node(self, "K2Node_BreakStruct", self._auto("K2Node_BreakStruct"), x, y, {
            "StructType": obj("ScriptStruct", struct_path),
            "bMadeAfterOverridePinRemoval": "True",
        })
        n.pin(nombre_pin_entrada, CAT_STRUCT,
              sub_object=obj("ScriptStruct", struct_path))
        return n

    def literal_enum(self, enum_path, entrada_interna, x=0, y=0):
        """Nodo de constante de enum (el desplegable suelto)."""
        n = Node(self, "K2Node_EnumLiteral", self._auto("K2Node_EnumLiteral"), x, y, {
            "Enum": obj("Enum", enum_path),
        })
        n.pin("Enum", CAT_BYTE, sub_object=obj("Enum", enum_path),
              default=entrada_interna)
        n.pin("ReturnValue", CAT_BYTE, out=True, sub_object=obj("Enum", enum_path))
        return n

    def node_sequence(self, x=0, y=0, n=2):
        """Nodo Sequence: una entrada, N salidas que se ejecutan en orden.

        Util para que un bucle sobreviva a un salto: si la rama que se
        reprograma va en then_0 y lleva un Delay (que es latente y cede el
        control), then_1 puede saltar a otro evento sin matar el bucle.
        """
        node = Node(self, "K2Node_ExecutionSequence",
                    self._auto("K2Node_ExecutionSequence"), x, y)
        node.pin("execute", CAT_EXEC)
        for i in range(n):
            node.pin("then_%d" % i, CAT_EXEC, out=True)
        return node

    MACROS_ESTANDAR = "/Engine/EditorBlueprintResources/StandardMacros.StandardMacros"

    def macro(self, nombre_macro, x=0, y=0):
        """Instancia de una macro de la biblioteca estandar (ForEachLoop,
        IsValid, DoOnce...).

        La referencia lleva DOS rutas y las dos van con el envoltorio entre
        comillas dobles, tal y como las escribe el exportador:
            MacroGraphReference=(
              MacroGraph="/Script/Engine.EdGraph'<biblioteca>:<Macro>'",
              GraphBlueprint="/Script/Engine.Blueprint'<biblioteca>'")
        Los pines NO se reconstruyen solos como en K2Node_CallFunction: hay
        que declararlos todos, y con el nombre exacto (ojo a los que llevan
        espacio, como "Array Element").
        """
        lib = self.MACROS_ESTANDAR
        return Node(self, "K2Node_MacroInstance",
                    self._auto("K2Node_MacroInstance"), x, y, {
                        "MacroGraphReference":
                            '(MacroGraph="/Script/Engine.EdGraph\'%s:%s\'",'
                            'GraphBlueprint="/Script/Engine.Blueprint\'%s\'")'
                            % (lib, nombre_macro, lib),
                    })

    def for_each(self, x=0, y=0, category=CAT_OBJECT, sub_object=None):
        """ForEachLoop sobre un array. Pines: Exec / Array -> LoopBody +
        'Array Element' + 'Array Index', y Completed al terminar."""
        n = self.macro("ForEachLoop", x, y)
        n.pin("Exec", CAT_EXEC)
        n.pin("Array", category, sub_object=sub_object, container="Array")
        n.pin("LoopBody", CAT_EXEC, out=True)
        n.pin("Array Element", category, out=True, sub_object=sub_object)
        n.pin("Array Index", CAT_INT, out=True)
        n.pin("Completed", CAT_EXEC, out=True)
        return n

    def is_valid(self, x=0, y=0, sub_object=None):
        """Macro IsValid. Pines: Exec / InputObject -> 'Is Valid' +
        'Is Not Valid'."""
        n = self.macro("IsValid", x, y)
        n.pin("Exec", CAT_EXEC)
        n.pin("InputObject", CAT_OBJECT,
              sub_object=sub_object or cls("/Script/CoreUObject.Object"))
        n.pin("Is Valid", CAT_EXEC, out=True)
        n.pin("Is Not Valid", CAT_EXEC, out=True)
        return n

    def input_action(self, input_action_ref, x=0, y=0):
        """Nodo de Enhanced Input (el de los cinco triangulos: Triggered,
        Started, Ongoing, Canceled, Completed).

        OJO con dos cosas:
        - la clase vive en el modulo InputBlueprintNodes, no en BlueprintGraph;
        - la propiedad InputAction quiere la forma con envoltorio y comillas
          dobles por fuera, tal y como la escribe el exportador:
          InputAction="/Script/EnhancedInput.InputAction'/Game/.../IA_X.IA_X'"
          (no es el mismo formato que DefaultObject, que va pelado).
        """
        n = Node(self, "K2Node_EnhancedInputAction",
                 self._auto("K2Node_EnhancedInputAction"), x, y, {
                     "InputAction": '"%s"' % input_action_ref,
                 }, module="InputBlueprintNodes")
        for salida in ("Triggered", "Started", "Ongoing", "Canceled", "Completed"):
            n.pin(salida, CAT_EXEC, out=True)
        n.pin("ActionValue", CAT_STRUCT, out=True,
              sub_object=obj("ScriptStruct", "/Script/EnhancedInput.InputActionValue"))
        n.pin("ElapsedSeconds", CAT_REAL, out=True, sub="double")
        n.pin("TriggeredSeconds", CAT_REAL, out=True, sub="double")
        return n

    def comment(self, texto, x, y, w, h, color="(R=0.000000,G=0.000000,B=0.000000,A=0.400000)"):
        n = Node(self, "EdGraphNode_Comment", self._auto("EdGraphNode_Comment"), x, y, {
            "NodeWidth": str(w),
            "NodeHeight": str(h),
            "CommentColor": color,
            "NodeComment": '"%s"' % esc(texto),
            "bCommentBubbleVisible_InDetailsPanel": "False",
        }, module="UnrealEd")
        return n

    # ------------------------------------------------------------- salida
    def render(self):
        cab = []
        if self.titulo:
            for linea in self.titulo.strip().split("\n"):
                cab.append("// " + linea)
            cab.append("")
        cuerpo = "\n".join(n.render() for n in self.nodes)
        return "\n".join(cab) + cuerpo + "\n"

    def save(self, path):
        with open(path, "w", encoding="utf-8") as f:
            f.write(self.render())
        return path
